package com.frizo.lab.mybatis.mapper;

import com.frizo.lab.mybatis.model.SysRolePrivilege;
import java.util.List;

public interface SysRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated
     */
    int insert(SysRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated
     */
    List<SysRolePrivilege> selectAll();
}